name: app
description: Julia Set Generator, Flutter and Python Integration example.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  grpc: ^3.2.4
  path: ^1.8.3
  path_provider: ^2.1.1
  protobuf: ^3.1.0
  popover: ^0.2.8+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Fraps
      fonts:
        - asset: assets/fraps.otf
  assets:
    - assets/
  
