# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_generator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13set_generator.proto\"V\n\x10HeightMapRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\x12\x11\n\tthreshold\x18\x03 \x01(\x05\x12\x10\n\x08position\x18\x04 \x01(\x02\"9\n\x11HeightMapResponse\x12\x12\n\nheight_map\x18\x01 \x03(\x05\x12\x10\n\x08position\x18\x02 \x01(\x02\x32\x9e\x01\n\x18JuliaSetGeneratorService\x12<\n\x11GetSetAsHeightMap\x12\x11.HeightMapRequest\x1a\x12.HeightMapResponse\"\x00\x12\x44\n\x17GetSetAsHeightMapStream\x12\x11.HeightMapRequest\x1a\x12.HeightMapResponse\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HEIGHTMAPREQUEST']._serialized_start=23
  _globals['_HEIGHTMAPREQUEST']._serialized_end=109
  _globals['_HEIGHTMAPRESPONSE']._serialized_start=111
  _globals['_HEIGHTMAPRESPONSE']._serialized_end=168
  _globals['_JULIASETGENERATORSERVICE']._serialized_start=171
  _globals['_JULIASETGENERATORSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
