# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import set_generator_pb2 as set__generator__pb2


class JuliaSetGeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSetAsHeightMap = channel.unary_unary(
                '/JuliaSetGeneratorService/GetSetAsHeightMap',
                request_serializer=set__generator__pb2.HeightMapRequest.SerializeToString,
                response_deserializer=set__generator__pb2.HeightMapResponse.FromString,
                )
        self.GetSetAsHeightMapStream = channel.unary_stream(
                '/JuliaSetGeneratorService/GetSetAsHeightMapStream',
                request_serializer=set__generator__pb2.HeightMapRequest.SerializeToString,
                response_deserializer=set__generator__pb2.HeightMapResponse.FromString,
                )
        self.GetSetAsHeightMapAsBytesStream = channel.unary_stream(
                '/JuliaSetGeneratorService/GetSetAsHeightMapAsBytesStream',
                request_serializer=set__generator__pb2.HeightMapRequest.SerializeToString,
                response_deserializer=set__generator__pb2.HeightMapBytesResponse.FromString,
                )


class JuliaSetGeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetSetAsHeightMap(self, request, context):
        """Accepts Width and Height parameters, returns a 'height map', i.e. for each pixel how many iterations happened
        before the algo stopped checking for divergance. The more iterations, the higher the magnitude
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSetAsHeightMapStream(self, request, context):
        """Infinetly streams frames 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSetAsHeightMapAsBytesStream(self, request, context):
        """Infinetly streams frames, use bytes rather than list of int32
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JuliaSetGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSetAsHeightMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSetAsHeightMap,
                    request_deserializer=set__generator__pb2.HeightMapRequest.FromString,
                    response_serializer=set__generator__pb2.HeightMapResponse.SerializeToString,
            ),
            'GetSetAsHeightMapStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSetAsHeightMapStream,
                    request_deserializer=set__generator__pb2.HeightMapRequest.FromString,
                    response_serializer=set__generator__pb2.HeightMapResponse.SerializeToString,
            ),
            'GetSetAsHeightMapAsBytesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.GetSetAsHeightMapAsBytesStream,
                    request_deserializer=set__generator__pb2.HeightMapRequest.FromString,
                    response_serializer=set__generator__pb2.HeightMapBytesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JuliaSetGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JuliaSetGeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetSetAsHeightMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JuliaSetGeneratorService/GetSetAsHeightMap',
            set__generator__pb2.HeightMapRequest.SerializeToString,
            set__generator__pb2.HeightMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSetAsHeightMapStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/JuliaSetGeneratorService/GetSetAsHeightMapStream',
            set__generator__pb2.HeightMapRequest.SerializeToString,
            set__generator__pb2.HeightMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSetAsHeightMapAsBytesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/JuliaSetGeneratorService/GetSetAsHeightMapAsBytesStream',
            set__generator__pb2.HeightMapRequest.SerializeToString,
            set__generator__pb2.HeightMapBytesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
