# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import set_generator_pb2 as set__generator__pb2


class JuliaSetGeneratorServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHeightMap = channel.unary_unary(
                '/JuliaSetGeneratorService/GetHeightMap',
                request_serializer=set__generator__pb2.HeightMapRequest.SerializeToString,
                response_deserializer=set__generator__pb2.HeightMapResponse.FromString,
                )


class JuliaSetGeneratorServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHeightMap(self, request, context):
        """Accepts Width and Height parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_JuliaSetGeneratorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetHeightMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHeightMap,
                    request_deserializer=set__generator__pb2.HeightMapRequest.FromString,
                    response_serializer=set__generator__pb2.HeightMapResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'JuliaSetGeneratorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class JuliaSetGeneratorService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHeightMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/JuliaSetGeneratorService/GetHeightMap',
            set__generator__pb2.HeightMapRequest.SerializeToString,
            set__generator__pb2.HeightMapResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
