# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: set_generator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13set_generator.proto\"1\n\x10HeightMapRequest\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\'\n\x11HeightMapResponse\x12\x12\n\nheight_map\x18\x01 \x03(\x02\x32S\n\x18JuliaSetGeneratorService\x12\x37\n\x0cGetHeightMap\x12\x11.HeightMapRequest\x1a\x12.HeightMapResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'set_generator_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_HEIGHTMAPREQUEST']._serialized_start=23
  _globals['_HEIGHTMAPREQUEST']._serialized_end=72
  _globals['_HEIGHTMAPRESPONSE']._serialized_start=74
  _globals['_HEIGHTMAPRESPONSE']._serialized_end=113
  _globals['_JULIASETGENERATORSERVICE']._serialized_start=115
  _globals['_JULIASETGENERATORSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
